name: Android One Click APK

on:
  workflow_dispatch:  # <-- shows the "Run workflow" button
  # You can also auto-build on every push by uncommenting:
  # push:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable (just in case)
        run: chmod +x android/gradlew

      - name: Build Debug APK
        working-directory: android
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: lyricsmith-apk
          path: android/app/build/outputs/apk/debug/*.apk
