name: Android — One Click APK
on: { workflow_dispatch: {} }
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - name: Build Debug APK
        run: |
          cd android
          ./gradlew --no-daemon assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: lyricsmith-apk
          path: android/app/build/outputs/apk/debug/*.apk
