name: Android One Click APK

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: Debug or Release
        required: false
        default: debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK (cmdline-tools)
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Configure AndroidX flags
        run: |
          echo "android.useAndroidX=true" >> android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties

      - name: Make Gradle wrapper executable
        run: chmod +x android/gradlew

      - name: Build Debug APK
        if: ${{ github.event.inputs.buildType == 'debug' || github.event.inputs.buildType == '' }}
        working-directory: android
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload Debug APK
        if: ${{ github.event.inputs.buildType == 'debug' || github.event.inputs.buildType == '' }}
        uses: actions/upload-artifact@v4
        with:
          name: LyricSmith-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Build Release APK
        if: ${{ github.event.inputs.buildType == 'release' }}
        working-directory: android
        run: ./gradlew --no-daemon assembleRelease

      - name: Upload Release APK
        if: ${{ github.event.inputs.buildType == 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: LyricSmith-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
